# Generated by Django 5.2 on 2025-04-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='media/My Snapshot.jpg', null=True, upload_to=''),
        ),
    ]
