# Generated by Django 5.2 on 2025-04-30 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
